apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-rolling.yml
  target:
    group: argoproj.io
    kind: Rollout
    version: v1alpha1

images:
- name: adservice
  newName: gcr.io/gke-demo-pwei1018/adservice
  newTag: 060d41a
- name: cartservice
  newName: gcr.io/gke-demo-pwei1018/cartservice
  newTag: 060d41a
- name: checkoutservice
  newName: gcr.io/gke-demo-pwei1018/checkoutservice
  newTag: 060d41a
- name: currencyservice
  newName: gcr.io/gke-demo-pwei1018/currencyservice
  newTag: 060d41a
- name: emailservice
  newName: gcr.io/gke-demo-pwei1018/emailservice
  newTag: 060d41a
- name: frontend
  newName: gcr.io/gke-demo-pwei1018/frontend
  newTag: 060d41a
- name: paymentservice
  newName: gcr.io/gke-demo-pwei1018/paymentservice
  newTag: 060d41a
- name: productcatalogservice
  newName: gcr.io/gke-demo-pwei1018/productcatalogservice
  newTag: 060d41a
- name: recommendationservice
  newName: gcr.io/gke-demo-pwei1018/recommendationservice
  newTag: 060d41a
- name: redis
  newName: redis
  newTag: 5.0.7-alpine3.11
- name: shippingservice
  newName: gcr.io/gke-demo-pwei1018/shippingservice
  newTag: 060d41a
